function aa () {
    try {
        let a = 5
        console.log('e',a)
        return 
    } catch (error) {
        
    } finally {
        console.log('e')
    }
}
aa()